# Generated by Django 4.0.2 on 2022-02-27 07:55

import django.core.validators
from django.db import migrations, models
import myexam.web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), myexam.web.models.validate_username])),
                ('Email', models.EmailField(max_length=254)),
                ('Age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
