# Generated by Django 4.0.2 on 2022-02-27 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_Name', models.CharField(max_length=30, unique=True)),
                ('Artist', models.CharField(max_length=30)),
                ('Genre', models.CharField(choices=[('Pop Music', 'Pop Music'), ('Jazz Music', 'Jazz Music'), ('R&B Music', 'R&B Music'), ('Rock Music', 'Rock Music'), ('Country Music', 'Country Music'), ('Dance Music', 'Dance Music'), ('Hip Hop Music', 'Hip Hop Music'), ('Other', 'Other')], max_length=30)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Image_URL', models.URLField()),
                ('Price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
