# Generated by Django 4.0.2 on 2022-02-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('Album_Name',)},
        ),
    ]
